<?php

use Illuminate\Database\Seeder;

class AreasTableSeeder extends Seeder
{
    public function run()
    {
        $now = \Carbon\Carbon::now();
        $areas = [
            [1,'Abogacía / Derecho / Leyes'],
            [2,'Actuaría'],
            [3,'Acuicultura'],
            [4,'Adm. de Empresas'],
            [5,'Adm. y Gestión Pública'],
            [6,'Administración Agropecuaria'],
            [7,'Agrimensor'],
            [8,'Agronegocios'],
            [9,'Antropología'],
            [10,'Análisis de Sistemas'],
            [11,'Apoderado Aduanal'],
            [12,'Arqueología'],
            [13,'Arquitectura'],
            [14,'Asesoría Legal Internacional'],
            [15,'Asesoría de Comercio Exterior'],
            [16,'Asesoría de Comercio Exterior Jubilado'],
            [17,'Asistente de Tráfico'],
            [18,'Astronomía'],
            [19,'Bachiller'],
            [20,'Bacteriología'],
            [21,'Bellas Artes'],
            [22,'Bibliotecnología'],
            [23,'BioFisica'],
            [24,'BioIngeniería'],
            [25,'Biología'],
            [26,'Bioquímica'],
            [27,'Biotecnología'],
            [28,'Call Center'],
            [29,'Capacitación Comercio Exterior'],
            [30,'Cartografía'],
            [31,'Ciencias Físicas'],
            [33,'Ciencias Políticas'],
            [34,'Ciencias de la Educación'],
            [35,'Ciencias del Ejercicio/Educación Física'],
            [36,'Comercio int./Ext.'],
            [37,'Compras Internacionales/Importación'],
            [38,'Computación / Informática'],
            [39,'Comunicación Audiovisual'],
            [40,'Comunicación Social'],
            [41,'Construcción / Obras Civiles'],
            [42,'Consultorías Comercio Exterior'],
            [43,'Contabilidad / Auditoría'],
            [44,'Dibujo Técnico'],
            [45,'Diseño Gráfico'],
            [46,'Diseño Industrial'],
            [47,'Diseño Web'],
            [48,'Diseño de imagen y Sonido'],
            [49,'Diseño de Vestuario / Textil / Modas'],
            [50,'Ecología'],
            [51,'Economía'],
            [52,'Educación'],
            [53,'Electricidad'],
            [54,'Electrónica'],
            [55,'Enfermería'],
            [56,'Enología'],
            [57,'Escribanía'],
            [58,'Estadística'],
            [59,'Farmacia'],
            [60,'Filosofía'],
            [61,'Finanzas'],
            [62,'Finanzas Internacionales'],
            [63,'Fisioterapia'],
            [64,'Fonoaudiología'],
            [65,'Fotografía'],
            [66,'Gastronomía / Cocina'],
            [67,'Geofísica'],
            [68,'Geografía'],
            [69,'Geología / Geomensura / Topografía'],
            [70,'Hidráulica'],
            [71,'Histopatología'],
            [72,'Historia'],
            [73,'Hotelería'],
            [74,'Ing. - otros'],
            [75,'Ing. Aerospacial'],
            [76,'Ing. Agropecuario'],
            [77,'Ing. Agrónomo'],
            [78,'Ing. Alimentos'],
            [79,'Ing. Ambiental'],
            [80,'Ing. Comercial'],
            [81,'Ing. Electrónica'],
            [82,'Ing. Eléctrica'],
            [83,'Ing. Forestal'],
            [84,'Ing. Hidraúlica'],
            [85,'Ing. Industrial'],
            [86,'Ing. Informática'],
            [87,'Ing. Matemática'],
            [88,'Ing. Mecánica/Metalúrgica'],
            [89,'Ing. Naval'],
            [90,'Ing. Nuclear'],
            [91,'Ing. Obras Civiles / Construcción'],
            [92,'Ing. Pesquera / Cultivos Marinos'],
            [93,'Ing. Petróleo'],
            [94,'Ing. Química'],
            [95,'Ing. Recursos Humanos'],
            [96,'Ing. Sonido'],
            [97,'Ing. Telecomunicaciones'],
            [98,'Ing. Transporte'],
            [99,'Ing. Materiales'],
            [100,'Ing. Minas'],
            [101,'Ing. en Sistemas'],
            [102,'Ingeniero en Construcción'],
            [103,'Ingeniero Vial'],
            [104,'Intérprete'],
            [105,'Kinesiología'],
            [106,'Laboratorio (Mecánica) Dental'],
            [107,'Literatura'],
            [108,'Maestro Mayor de Obras'],
            [109,'Marketing / Comercialización'],
            [110,'Matemáticas'],
            [111,'Mecánica / Metalúrgica'],
            [112,'Medicina'],
            [113,'Medio Ambiente'],
            [114,'Mercadotecnia Internacional'],
            [115,'Microbiología'],
            [116,'Minería / Petróleo / Gas'],
            [117,'Música'],
            [118,'Nutrición'],
            [119,'Oceanografía'],
            [120,'Odontología'],
            [121,'Organización Industrial'],
            [122,'Otra'],
            [123,'Paisajismo'],
            [124,'Periodismo'],
            [125,'Perito Mercantil'],
            [126,'Procesos / Calidad Total'],
            [127,'Programación'],
            [128,'Psicología'],
            [129,'Psicopedagogía'],
            [130,'Publicidad'],
            [131,'Química'],
            [132,'Químico Farmacéutico'],
            [133,'Recursos Humanos / Relac. Ind.'],
            [134,'Relaciones Internacionales'],
            [135,'Relaciones Públicas'],
            [136,'Salud'],
            [137,'Secretariado'],
            [138,'Seguridad Industrial'],
            [139,'Seguros'],
            [140,'Sociología'],
            [141,'Técnico'],
            [142,'Tecnología Médica / Laboratorio'],
            [143,'Tecnología de Alimentos'],
            [144,'Tenconogías de la Información'],
            [145,'Telecominicaciones'],
            [146,'Terapia Ocupacional'],
            [147,'Trabajo Social'],
            [148,'Traducción'],
            [149,'Transporte'],
            [150,'Turísmo'],
            [151,'Ventas Internacionales/Exportación'],
            [152,'Veterinaria'],
        ];
        $areas = array_map(function($area) use ($now){
           return [
               'id' => $area[0],
               'nombre' => $area[1],
               'updated_at' => $now,
               'created_at' => $now,
           ];
        }, $areas);
        \DB::table('areas')->insert($areas);
    }
}
