<?php

use Illuminate\Database\Seeder;

class InstitucionesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        $now = \Carbon\Carbon::now();
        $instituciones = [
            [1,'Universidad de Chile '],
            [2,'Universidad de Santiago de Chile '],
            [3,'Universidad de Valparaíso '],
            [4,'Universidad de Antofagasta'],
            [5,'Universidad de La Serena'],
            [6,'Universidad del Bío-Bío '],
            [7,'Universidad de La Frontera '],
            [8,'Universidad de Magallanes'],
            [9,'Universidad de Talca'],
            [10,'Universidad de Atacama '],
            [11,'Universidad de Tarapacá '],
            [12,'Universidad Arturo Prat'],
            [13,'Universidad Metropolitana de Ciencias de la Educación'],
            [14,'Universidad de Playa Ancha de Ciencias de la Educación '],
            [15,'Universidad de Los Lagos'],
            [16,'Universidad Tecnológica Metropolitana'],
            [17,'Universidad de OHiggins'],
            [18,'Universidad de Aysén '],
            [19,'Pontificia Universidad Católica de Chile'],
            [20,'Universidad de Concepción'],
            [21,'Universidad Técnica Federico Santa María'],
            [22,'Pontificia Universidad Católica de Valparaíso'],
            [23,'Universidad Austral de Chile '],
            [24,'Universidad Católica del Norte'],
            [25,'Universidad Católica del Maule'],
            [26,'Universidad Católica de la Santísima Concepción'],
            [27,'Universidad Católica de Temuco'],
            [28,'Universidad Gabriela Mistral'],
            [29,'Universidad Finis Terrae'],
            [30,'Universidad Diego Portales '],
            [31,'Universidad Central de Chile'],
            [33,'Universidad Bolivariana'],
            [34,'Universidad Pedro de Valdivia'],
            [35,'Universidad Mayor'],
            [36,'Universidad Academia de Humanismo Cristiano'],
            [37,'Universidad Santo Tomás'],
            [38,'Universidad La República'],
            [39,'Universidad Sek'],
            [40,'Universidad de Las Américas'],
            [41,'Universidad Andrés Bello'],
            [42,'Universidad de Viña del Mar'],
            [43,'Universidad Adolfo Ibañez'],
            [44,'Universidad Iberoamericana de Ciencias y Tecnología, UNICIT'],
            [45,'Universidad de Artes, Ciencias y Comunicación - UNIACC'],
            [46,'Universidad UCINF'],
            [47,'Universidad Autónoma de Chile'],
            [48,'Universidad de Los Andes'],
            [49,'Universidad Adventista de Chile'],
            [50,'Universidad San Sebastián'],
            [51,'Universidad de Arte y Ciencias Sociales ARCIS'],
            [52,'Universidad Católica Cardenal Raúl Silva Henríquez'],
            [53,'Universidad del Desarrollo'],
            [54,'Universidad de Aconcagua'],
            [55,'Universidad del Pacífico'],
            [56,'Universidad Los Leones'],
            [57,'Universidad Bernardo OHiggins'],
            [58,'Universidad Tecnológica de Chile INACAP'],
            [59,'Universidad Miguel de Cervantes'],
            [60,'Universidad Alberto Hurtado'],
            [61,'Universidad Chileno Británica de Cultura'],
            [62,'Instituto Profesional Agrario Adolfo Matthei'],
            [63,'Instituto Profesional INACAP'],
            [64,'Instituto Profesional Libertador de Los Andes'],
            [65,'Instituto Profesional Instituto de Estudios Bancarios Guillermo Subercaseaux'],
            [66,'Instituto Profesional Escuela de Contadores Auditores de Santiago'],
            [67,'Instituto Profesional Providencia'],
            [68,'Instituto Profesional Chileno Británico de Cultura'],
            [69,'Instituto Profesional Adventista'],
            [70,'Instituto Profesional DUOC UC'],
            [71,'Instituto Profesional IPG'],
            [72,'Instituto Profesional Santo Tomás'],
            [73,'Instituto Profesional Instituto Superior de Artes y Ciencias de la Comunicación'],
            [74,'Instituto Profesional Alemán Wilhelm Von Humboldt'],
            [75,'Instituto Profesional Diego Portales'],
            [76,'Instituto Profesional de Chile'],
            [77,'Instituto Profesional La Araucana'],
            [78,'Instituto Profesional Escuela Moderna de Música'],
            [79,'Instituto Profesional de Ciencias y Artes INCACEA'],
            [80,'Instituto Profesional ESUCOMEX'],
            [81,'Instituto Profesional de ENAC'],
            [82,'Instituto Profesional EATRI Instituto Profesional'],
            [83,'Instituto Profesional de Los Angeles'],
            [84,'Instituto Profesional Dr. Virginio Gómez G.'],
            [85,'Instituto Profesional de Ciencias y Educación Helen Keller'],
            [86,'Instituto Profesional AIEP'],
            [87,'Instituto Profesional de Arte y Comunicación ARCOS '],
            [88,'Instituto Profesional Hogar Catequístico'],
            [89,'Instituto Profesional Latinoamericano de Comercio Exterior - IPLACEX'],
            [90,'Instituto Profesional Los Leones'],
            [91,'Instituto Profesional CIISA'],
            [92,'Instituto Profesional Los Lagos'],
            [93,'Instituto Profesional de Ciencias de la Computación Acuario Data'],
            [94,'Instituto Profesional del Comercio'],
            [95,'Instituto Profesional del Valle Central'],
            [96,'Instituto Profesional Carlos Casanueva'],
            [97,'Instituto Profesional Instituto Nacional del Fútbol'],
            [98,'Instituto Profesional Instituto Internacional de Artes Culinarias y Servicios'],
            [99,'Instituto Profesional PROJAZZ'],
            [100,'Instituto Profesional Chileno Norteamericano'],
            [101,'Instituto Profesional Escuela de Cine de Chile'],
            [102,'Instituto Profesional de Artes Escénicas Karen Connolly'],
            [103,'Instituto Profesional Mar Futuro'],
            [104,'Instituto Profesional Vertical Instituto Profesional'],
            [105,'Centro de Formación Técnica Instituto Central de Capacitación Educacional ICCE'],
            [106,'Centro de Formación Técnica de ENAC'],
            [107,'Centro de Formación Técnica DUOC UC'],
            [108,'Centro de Formación Técnica Juan Bohon'],
            [109,'Centro de Formación Técnica Barros Arana '],
            [110,'Centro de Formación Técnica Santo Tomás'],
            [111,'Centro de Formación Técnica Andrés Bello'],
            [112,'Centro de Formación Técnica Massachusetts'],
            [113,'Centro de Formación Técnica Los Lagos'],
            [114,'Centro de Formación Técnica Luis Alberto Vera'],
            [115,'Centro de Formación Técnica Estudio Profesor Valero'],
            [116,'Centro de Formación Técnica CENCO'],
            [117,'Centro de Formación Técnica ALFA'],
            [118,'Centro de Formación Técnica PRODATA'],
            [119,'Centro de Formación Técnica Instituto Superior de Estudios Jurídicos CANON'],
            [120,'Centro de Formación Técnica IPROSEC'],
            [121,'Centro de Formación Técnica San Agustín de Talca'],
            [122,'Centro de Formación Técnica ICEL'],
            [123,'Centro de Formación Técnica Alpes'],
            [124,'Centro de Formación Técnica Instituto Técnológico de Chile - I.T.C.'],
            [125,'Centro de Formación Técnica EDUCAP'],
            [126,'Centro de Formación Técnica Cámara de Comercio de Santiago'],
            [127,'Centro de Formación Técnica LAPLACE'],
            [128,'Centro de Formación Técnica INACAP'],
            [129,'Centro de Formación Técnica del Medio Ambiente'],
            [130,'Centro de Formación Técnica Lota-Arauco'],
            [131,'Centro de Formación Técnica CEDUC - UCN'],
            [132,'Centro de Formación Técnica UDA'],
            [133,'Centro de Formación Técnica CEITEC'],
            [134,'Centro de Formación Técnica PROANDES'],
            [135,'Centro de Formación Técnica de Tarapacá'],
            [136,'Centro de Formación Técnica U. Valpo'],
            [137,'Centro de Formación Técnica PROTEC'],
            [138,'Centro de Formación Técnica de la Industria Gráfica '],
            [139,'Centro de Formación Técnica UCEVALPO'],
            [140,'Centro de Formación Técnica Teodoro Wickel Kluwen'],
            [141,'Centro de Formación Técnica PROFASOC'],
            [142,'Centro de Formación Técnica MANPOWER'],
            [143,'Centro de Formación Técnica Escuela Culinaria Francesa'],
            [144,'Centro de Formación Técnica FINNING'],
            [145,'Centro de Formación Técnica de la Región del Maule'],
            [146,'Centro de Formación Técnica de la Región de La Araucanía'],
        ];
        $instituciones = array_map(function($institucion) use ($now){
           return [
               'id' => $institucion[0],
               'nombre' => $institucion[1],
               'updated_at' => $now,
               'created_at' => $now,
           ];
        }, $instituciones);
        \DB::table('instituciones')->insert($instituciones);
    }
}
